apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-vidtxt-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/Babbili/${PY_VIDTXT_RPO}
    targetRevision: HEAD
    kustomize:
      images:
      - Babbili/${VIDTXT}:latest
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
